[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
prediction_markets = "EhMD2NdBfgsrJmXUgxWwpQrWbAockZ4GAs5G5NkwCmsa"

[programs.localnet]
prediction_markets = "EhMD2NdBfgsrJmXUgxWwpQrWbAockZ4GAs5G5NkwCmsa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
create-demo-markets = "ts-node scripts/create-demo-markets.ts"